### ISSUE TITLE
Proxmox 8.2.4 not able to boot VM

### ISSUE THREAD

**Issue by thenewguy854** [jiangcuo/Proxmox-Port#102]
The latest version of Proxmox does not work with creating VMs and booting into them.
When I go to make a VM this is what happens. 
![Screenshot 2024-06-24 192755](https://github.com/jiangcuo/Proxmox-Port/assets/75702887/14b1d8dc-f7fc-449b-925d-9e7e013fa01c)

when I change the setting to turn off secure boot this is the screen. 
![Screenshot 2024-06-24 192952](https://github.com/jiangcuo/Proxmox-Port/assets/75702887/75440cc9-fc8c-4a87-b6ca-45544e37aed7)

**To Reproduce**
1. To reproduce I click create a VM
2. Name the VM then click next
3. Select local for storage and ubuntu-22.04.4-live-server-amd64.iso for the ISO then Linux for the type and version 6.x then click next
4. Change BIOS to OVMF (UEFI) and change EFI storage to local leaving all other setttings as default.
5. Click next leaving all other setting on defalt then confim and finish. 
6. start up VM where I get above errors when booting up the ISO. 

Linux server 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Jun 25 01:06:15 BST 2024 on pts/0
root@server:~# pveversion -v
proxmox-ve: 8.2.0 (running kernel: 6.6.31+rpt-rpi-2712)
pve-manager: 8.2.4 (running version: 8.2.4/0098b77b88c86db8)
proxmox-kernel-helper: 8.1.0
ceph-fuse: 17.2.6-pve1+3
corosync: 3.1.7-pve3
criu: 3.17.1-2
glusterfs-client: 10.3-5
ifupdown: residual config
ifupdown2: 3.2.0-1+pmx8
libjs-extjs: 7.0.0-4
libknet1: 1.28-pve1
libproxmox-acme-perl: 1.5.1
libproxmox-backup-qemu0: 1.4.0
libproxmox-rs-perl: 0.3.3
libpve-access-control: 8.1.4
libpve-apiclient-perl: 3.3.1
libpve-cluster-api-perl: 8.0.7
libpve-cluster-perl: 8.0.7
libpve-common-perl: 8.2.1
libpve-guest-common-perl: 5.1.3
libpve-http-server-perl: 5.1.0
libpve-network-perl: 0.9.8
libpve-rs-perl: 0.8.9
libpve-storage-perl: 8.2.1
libspice-server1: 0.15.1-1
lvm2: 2.03.16-2
lxc-pve: 6.0.0-1
lxcfs: 6.0.0-pve2
novnc-pve: 1.4.0-3
proxmox-backup-client: 3.2.5-1
proxmox-backup-file-restore: 3.2.4-1
proxmox-kernel-helper: 8.1.0
proxmox-mail-forward: 0.2.0
proxmox-mini-journalreader: 1.4.0
proxmox-offline-mirror-helper: 0.6.2
proxmox-widget-toolkit: 4.2.3
pve-cluster: 8.0.7
pve-container: 5.1.11
pve-docs: 8.2.2
pve-edk2-firmware: 4.2023.08-4
pve-firewall: 5.0.7
pve-firmware: not correctly installed
pve-ha-manager: 4.0.5
pve-i18n: 3.2.2
pve-qemu-kvm: 8.1.5-4
pve-xtermjs: 5.3.0-3
qemu-server: 8.2.1
smartmontools: 7.3-pve1
spiceterm: 3.3.0
swtpm: 0.8.0+pve1
vncterm: 1.8.0
zfsutils-linux: 2.2.4-pve1

This is all being done on a rasberrypi 5 8gb

**Comment by jiangcuo** [comment]
Arm64 vm can't boot from amd64 iso.
