### ISSUE TITLE
pve 8.0.8 won't reboot

### ISSUE THREAD

**Issue by cDentGit** [jiangcuo/Proxmox-Port#11]
First of all really great job!

Thank you for the links to the "german" repositories.

I'm using proxmox-port on a H96max TV-box, an RK3318 with 4/64GB with Armbian 6.1.50.
With version pve 8.0.6 everything was just right, now it has changed to pve 8.0.8, and neither upgrade nor new installation allows a correct reboot. It seems to me, that the ports are closed, IP:8006, SSH and SCP. Which files can I investigate (and change) for such severe results.

**Comment by jiangcuo** [comment]
Can you collect your screen output, ttl output or syslog?

**Comment by cDentGit** [comment]
With pve 8.1.3 reboot problem solved.
