### ISSUE TITLE
When vm packets pass through 5w2, a large number of packets will be lost or the delay will increase

### ISSUE THREAD

**Issue by wartw** [jiangcuo/Proxmox-Port#110]
When vm packets pass through 5w2, a large number of packets will be lost or the delay will increase. Is there any help in handling this?  My device is Huawei 2280.  pve load is less than 40% vm load is less than 20%
The network card has used the highest 100g network card certified by Huawei.

**Comment by jiangcuo** [comment]
Please use the bug template to reorganize your issue
