### ISSUE TITLE
Failed to load "UEFI QEUM QEMU HARDDISK " and "UEFI QEUM QEMU CD-ROM "

### ISSUE THREAD

**Issue by Xdek198** [jiangcuo/Proxmox-Port#111]
Describe the bug
When i start a VM it doesn't boot the system there's error message:
![obraz](https://github.com/user-attachments/assets/0f2edfcb-4612-4e2c-bc30-ebe9cc8408f8)

To reproduce
My hardware is: Orange pi 5 plus 16GB and samsung evo plus 128GB SD card
My VM ISO is: Orangepi5plus_1.0.8_debian_bullseye_server_linux6.1.43.img
settings i use:
![System](https://github.com/user-attachments/assets/0af7dc57-45e5-4eae-941f-7af7c04f5804)
![Disk](https://github.com/user-attachments/assets/fb196346-6eea-4e10-aa64-0dffa7312577)
![Cpu](https://github.com/user-attachments/assets/8d20ed64-f3d1-4274-80f0-946f8ba37de8)
![Confirm](https://github.com/user-attachments/assets/c62e1cec-59f7-4f84-a6a0-06151a583370)
My software:
proxmox-ve: pve-manager/8.2.4/0098b77b88c86db8 (running kernel: 5.10.160-legacy-rk35xx)
Operating System: Armbian 24.5.1 bookworm         
ceph-common: 17.2.6-pve1+3
ceph-fuse: 17.2.6-pve1+3
corosync: 3.1.7-pve3
criu: 3.17.1-2
glusterfs-client: 10.3-5
glusterfs-common: 10.3-5
ifupdown2: 3.2.0-1+pmx8
libcephfs2: 17.2.6-pve1+3
libcfg7:arm64: 3.1.7-pve3
libcmap4:arm64: 3.1.7-pve3
libcorosync-common4:arm64: 3.1.7-pve3
libcpg4:arm64: 3.1.7-pve3
libglusterfs0:arm64: 10.3-5
libjs-extjs: 7.0.0-4
libjs-qrcodejs: 1.20230525-pve1
libknet1:arm64: 1.28-pve1
liblvm2cmd2.03:arm64: 2.03.16-2
libnozzle1:arm64: 1.28-pve1
libproxmox-acme-perl: 1.5.1
libproxmox-acme-plugins: 1.5.1
libproxmox-backup-qemu0: 1.4.0
libproxmox-rs-perl: 0.3.3
libpve-access-control: 8.1.4
libpve-apiclient-perl: 3.3.1
libpve-cluster-api-perl: 8.0.7
libpve-cluster-perl: 8.0.7
libpve-common-perl: 8.2.1
libpve-guest-common-perl: 5.1.3
libpve-http-server-perl: 5.1.0
libpve-notify-perl: 8.0.7
libpve-rs-perl: 0.8.9
libpve-storage-perl: 8.2.1
libpve-u2f-server-perl: 1.2.0
libquorum5:arm64: 3.1.7-pve3
librados2: 17.2.6-pve1+3
libradosstriper1: 17.2.6-pve1+3
librbd1: 17.2.6-pve1+3
librgw2: 17.2.6-pve1+3
libspice-server1:arm64: 0.15.1-1
libtpms0:arm64: 0.9.6+pve1
libvotequorum8:arm64: 3.1.7-pve3
lvm2: 2.03.16-2
lxc-pve: 6.0.0-1
lxcfs: 6.0.0-pve2
novnc-pve: 1.4.0-3
proxmox-archive-keyring: 3.0
proxmox-backup-client: 3.2.5-1
proxmox-backup-file-restore: 3.2.4-1
proxmox-kernel-helper: 8.1.0
proxmox-mail-forward: 0.2.0
proxmox-mini-journalreader: 1.4.0
proxmox-termproxy: 1.0.1
proxmox-ve: 8.2.0
proxmox-websocket-tunnel: 0.2.0-1
proxmox-widget-toolkit: 4.2.3
pve-cluster: 8.0.7
pve-container: 5.1.11
pve-docs: 8.2.2
pve-edk2-firmware-aarch64: 3.20220526-rockchip
pve-edk2-firmware-legacy: 4.2023.08-4
pve-edk2-firmware-ovmf: 4.2023.08-4
pve-firewall: 5.0.7
pve-ha-manager: 4.0.5
pve-i18n: 3.2.2
pve-lxc-syscalld: 1.3.0
pve-manager: 8.2.4
pve-qemu-kvm: 8.1.5-4
pve-xtermjs: 5.3.0-3
python3-ceph-argparse: 17.2.6-pve1+3
python3-ceph-common: 17.2.6-pve1+3
python3-cephfs: 17.2.6-pve1+3
python3-rados: 17.2.6-pve1+3
python3-rbd: 17.2.6-pve1+3
python3-rgw: 17.2.6-pve1+3
smartmontools: 7.3-pve1
spice-vdagent: 0.22.1-3+b2
spiceterm: 3.3.0
swtpm: 0.8.0+pve1
swtpm-libs:arm64: 0.8.0+pve1
swtpm-tools: 0.8.0+pve1

**Comment by Xdek198** [comment]
> Please use the bug template to reorganize your issue
Is it ok now or something else is needed?

**Comment by Xdek198** [comment]
> Please use the bug template to reorganize your issue

Is it ok now or something else is needed?

**Comment by jiangcuo** [comment]
Don't enable [Pre-Enroll Key]

**Comment by Xdek198** [comment]
It didn't help

**Comment by jiangcuo** [comment]
Is  "Orangepi5plus_1.0.8_debian_bullseye_server_linux6.1.43.img" EFI ISO?


https://github.com/jiangcuo/Proxmox-Arm64/wiki/Qemu-VM

**Comment by Xdek198** [comment]
Yep that's it. I was thinking I need to use iso for orange pi 5 plus. Using official Ubuntu server arm iso worked. Thanks for helping. I appreciate your work.
