### ISSUE TITLE
[Tested] HPE RL300 - Ampere Altra Q80-30

### ISSUE THREAD

**Issue by isnuryusuf** [jiangcuo/Proxmox-Port#12]
Hi

Thank for the repo, just want to share i was successfully test run Virtual Environment 8.1.3 on top of HPE RL300 using  Ampere Altra M128-30

additional command:

apt-get update
apt-get install pve-edk2-firmware-aarch64

![image](https://github.com/jiangcuo/Proxmox-Port/assets/5492467/e09b9a6d-5034-44d6-992c-5861ffeca097)

Current Issue, CPU Information not show on Proxmox UI

![image](https://github.com/jiangcuo/Proxmox-Port/assets/5492467/c75d12fc-aa03-4a0e-87cc-1344f86f76f0)

**Comment by jiangcuo** [comment]
Is this issue same as  https://github.com/jiangcuo/Proxmox-Arm64/issues/60 ?

**Comment by isnuryusuf** [comment]
Its works, thank you

apt upgrade pve-manager && reboot

![image](https://github.com/jiangcuo/Proxmox-Port/assets/5492467/3cf65e9f-611f-494b-90d0-766417ec2ce0)
