### ISSUE TITLE
Virtual machine does not see USB devices

### ISSUE THREAD

**Issue by pro100805** [jiangcuo/Proxmox-Port#135]
Hello, thank you for your labours.
The problem is that the virtual machine does not see USB devices, no matter how it is routed. At the same time, the host sees these devices. 
Version 8.2.7 problems were but not constant
After the 8.3.0 update the connection was lost completely.
It does not depend on how the device is forwarded by ID or by specifying a specific USB port number.

 - OS: Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64
 - ARCH: arm64 (Rasp pi4 8G)
 - Version 8.3.0

**Comment by jiangcuo** [comment]
Please provide detailed information, such as virtual machine configuration, physical machine configuration, `lsusb -t`, `lspci` and so on.

**Comment by pro100805** [comment]
hi, This is from host, physical rasp. P4. Two devices flash drive and 4G modem
****:~# lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
    |__ Port 1: Dev 2, If 0, Class=Mass Storage, Driver=usbfs, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 4: Dev 3, If 0, Class=Vendor Specific Class, Driver=usbfs, 480M
        |__ Port 4: Dev 3, If 1, Class=Vendor Specific Class, Driver=usbfs, 480M
****:~# lspci
00:00.0 PCI bridge: Broadcom Inc. and subsidiaries BCM2711 PCIe Bridge (rev 20)
01:00.0 USB controller: VIA Technologies, Inc. VL805/806 xHCI USB 3.0 Controller (rev 01)

**Comment by pro100805** [comment]
is a virtual computer Ubuntu
![Ubuntu](https://github.com/user-attachments/assets/d6123d68-9f1e-4857-88d0-c1e062ac6745)

**Comment by pro100805** [comment]
![Ubuntu-2](https://github.com/user-attachments/assets/95ca1dac-1a1c-44a8-b46f-dffdd76fae8b)

**Comment by pro100805** [comment]
The 4g modem is used in conjunction with a virtual router, and before the update everything worked more or less stable
tell me what other information I can provide ...
best regards

**Comment by jiangcuo** [comment]
Pls upgrade qemu-server to latest version

**Comment by pro100805** [comment]
hi
from repositories that I know of, I managed to update to version -
qemu-system-arm --version
QEMU emulator version 9.0.2 (pve-qemu-kvm_9.0.2-3)
after that the situation changed VM Ubuntu saw the flash drive
but the VM with the router does not see the modem and as an experiment the VM with Windows 11 does not see the flash drives
I've tried to find other repositories, but no luck. 
I also tried to build from the sources but unfortunately my level is not that good
please tell me how to get the latest version of qemu-server

**Comment by pro100805** [comment]
hello, by running this command: sudo apt search qemu-server

I get the following response

Sorting... Done
Full Text Search... Done
libpve-guest-common-perl/unknown,now 5.1.6 all [installed,automatic]
  Proxmox VE common guest-related modules

qemu-server/unknown,now 8.3.3+port2 arm64 [installed,automatic]
  Qemu Server Tools

qemu-server-dbgsym/unknown 8.3.3+port2 arm64
  debug symbols for qemu-server

and : qemu-system-arm --version

I get the following response

QEMU emulator version 9.2.0 (pve-qemu-kvm_9.2.0-1+port2)
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers

virtual machine with router (and WIN 11) do not see USB devices, with virtual machine on Ubuntu everything is fine

**Comment by jiangcuo** [comment]
This is a Windows Arm issue. The device can only be recognized on pcie.0

https://github.com/jiangcuo/qemu-server/blob/e48ebea4570c64547cc1747523f6032e4d68e621/PVE/QemuServer/PCI.pm#L181

You can modify the bus number of this xhci to 0 and use an available addr.

**Comment by simper** [comment]
> This is a Windows Arm issue. The device can only be recognized on pcie.0
> 
> https://github.com/jiangcuo/qemu-server/blob/e48ebea4570c64547cc1747523f6032e4d68e621/PVE/QemuServer/PCI.pm#L181
> 
> You can modify the bus number of this xhci to 0 and use an available addr.

So that means a re-compilation of certain package after changing the bus/address number in referred code, or there is workaround to overwrite the xhci bus/address number on the file within existing configure file?
I tried to modify the VM conf file and add such line:
`args: -device ich9-usb-ehci1,id=usb,multifunction=on,bus=pci.0,addr=0xa`
but then the VM won't start with error:
`kvm: -device nec-usb-xhci,id=xhci,bus=pci.0,addr=0xd: Duplicate ID 'xhci' for device
TASK ERROR: start failed: QEMU exited with code 1`

**Comment by pro100805** [comment]
Hi, i have a virtual computer with an arm 64 router. In version 8.2.7 the modem connected via USB worked fine. After the update the router stopped seeing the USB modem. The hardware remains unchanged
