### ISSUE TITLE
How to setup a custom LXC repository

### ISSUE THREAD

**Issue by asylumexp** [jiangcuo/Proxmox-Port#151]
I can see that Proxmox-Port uses a custom LXC repository to get the lxc templates in Proxmox, how do you make this possible? I wanted to create my own for [this project](https://github.com/asylumexp/proxmox)

**Comment by jiangcuo** [comment]
You can see build.sh and lxc.json on
https://mirrors.apqa.cn/proxmox/lxcs/

and this patch
https://github.com/jiangcuo/Proxmox-Port/blob/Port/packages/pve-manager/patches/002-add-lxc-for-arm-source.patch

**Comment by asylumexp** [comment]
Okay, thank you for the help.
