### ISSUE TITLE
分辨率异常

### ISSUE THREAD

**Issue by kaidegit** [jiangcuo/Proxmox-Port#20]
在进入图形化安装的时候分辨率会有问题，显示不全影响安装

机子是华为W510，鲲鹏920，景嘉微JM7201，hdmi和vga都有这个问题
镜像用的是proxmox-ve_8.1-3_arm64.iso

![IMG_0548](https://github.com/jiangcuo/Proxmox-Port/assets/60053077/a88dd27c-3fa7-4da7-a086-e3caca33232c)
![IMG_0549](https://github.com/jiangcuo/Proxmox-Port/assets/60053077/cbf2fd11-f2ab-4984-9652-c0d359de3124)

**Comment by jiangcuo** [comment]
no JM7201  driver in kernel .
pls use  console mode

**Comment by kaidegit** [comment]
tui其实也不是很正常。。单行太长被换行然后错位了密码填不上也安装不下去

搞了张a卡，然后8.1装不了，卡loading initial ramdisk，7.4倒是可以。。蛮奇怪
