### ISSUE TITLE
Using Ubuntu kernel

### ISSUE THREAD

**Issue by ayakael** [jiangcuo/Proxmox-Port#22]
First of all, many thanks for your work. It makes it much easier to maintain my arm64 server.

I was wondering why upstream kernel is used rather than Ubuntu's. Indeed, Torvald's kernel has some issues on my Cavium ThunderX system around IRQ, and moving to Ubuntu's solved my issues. Since Proxmox developpers use Ubuntu's, it might also be a good idea to do that.

**Comment by jiangcuo** [comment]
It's a good idea to use kernels from other distros, and they have teams to optimize kernels.
But the Ubuntu kernel is not an lts kernel.Probably I'll switch to the debian kernel

**Comment by jiangcuo** [comment]
pve-port-kernel provides a convenient framework for building kernels.
Users can build the appropriate kernel for themselves

**Comment by ayakael** [comment]
Indeed, that's what I did myself :) It looks like kernel 6.6 will both be a Ubuntu LTS and an upstream LTS.

**Comment by liberodark** [comment]
I agree ubuntu is not a good kernel we can just apply patch from PVE with upstream kernel.
Somme hardware need a specific kernel actually.
