### ISSUE TITLE
Creating VMs

### ISSUE THREAD

**Issue by nexusguy59** [jiangcuo/Proxmox-Port#24]
I am using an Orange Pi 5 for this just so you know. I am able to create Containers but VM don't seem to want to work or create. I am using the PiMOX method because this is a Pi correct?
 [VM on Pimox](https://i12bretro.github.io/tutorials/0712.html). Yes I know it's not the same as PiMOX, I was hoping some one had some instructions for creating a VM with this config.

I don't think I am doing anything wrong of sorts. Any help would be appreciated.
Michael

**Comment by jiangcuo** [comment]
https://github.com/jiangcuo/Proxmox-Port/wiki/Rockchip-device-NOTE
