### ISSUE TITLE
How to adjust the resolution of Windows 11 in the console

### ISSUE THREAD

**Issue by guoguo12343** [jiangcuo/Proxmox-Port#27]
How to adjust the resolution of Windows 11 in the console？
![1704872380489](https://github.com/jiangcuo/Proxmox-Port/assets/36734788/57bbdb94-3576-4e9d-9e9a-31de98753891)
I modified this resolution in the BIOS menu. I don't understand why there are so few resolution options.
![1704872782528](https://github.com/jiangcuo/Proxmox-Port/assets/36734788/abfbf0b1-e66e-4a60-9d40-0a3443dedf38)
The current resolution displayed in Windows has indeed increased.But the resolution of noVNC is still very low in full screen mode.
![image](https://github.com/jiangcuo/Proxmox-Port/assets/36734788/62045daf-016e-400b-bc5f-a862602f96e5)

**Comment by jiangcuo** [comment]
Use virtio-gpu when driver has installed
https://www.bilibili.com/video/BV1he41127P7/?spm_id_from=333.337.search-card.all.click

**Comment by guoguo12343** [comment]
> Use virtio-gpu when driver has installed https://www.bilibili.com/video/BV1he41127P7/?spm_id_from=333.337.search-card.all.click

Thanks.That's too coincidental. This video was posted on the day I asked the question.
