### ISSUE TITLE
Is there a way to install proxmox Quorum on top of Debian?

### ISSUE THREAD

**Issue by Darin755** [jiangcuo/Proxmox-Port#29]
I am looking to add a 3rd node in a cluster that only is used to keep individual nodes in the cluster working. It doesn't need to be able to run VMs it just needs to serve as a third node.

**Comment by jiangcuo** [comment]
There is no qdevice in the current repo.
If you're going to use the version of arm, try compiling it by yourself
https://git.proxmox.com/?p=corosync-qdevice.git;a=summary

**Comment by Darin755** [comment]
Thanks for the information. Once I compile and install it is there a guide on how to join a existing cluster?
