### ISSUE TITLE
Does Pci Passthrough work ?

### ISSUE THREAD

**Issue by Abdelwahed-Aridj** [jiangcuo/Proxmox-Port#34]
am trying to pass-through internal wifi on raspberry pi 4 with no luck
ive tried both pve 8.1 and 7.4 on ssd and sd card
my goal is to use it on openwrt vm

**Comment by mrcheap1984** [comment]
This is the second ticket raised about passthrough. Last one raised two weeks ago.

https://github.com/jiangcuo/Proxmox-Port/issues/26#issue-2071499865

**Comment by jiangcuo** [comment]
https://github.com/jiangcuo/Proxmox-Port/wiki/Resource_PassThrough
