### ISSUE TITLE
No IOMMU passthrough

### ISSUE THREAD

**Issue by weat01** [jiangcuo/Proxmox-Port#37]
Get a black screen with flashing cursor when try and start an installer iso for 64bit (Kali) on raspberry pi 5 OS lite 64 bit (debian bookworm)
Trying to add a pci device, get this error - 
(There is no /etc/default/grub file to edit)
![image](https://github.com/jiangcuo/Proxmox-Port/assets/11367720/cf48b4d6-28fb-46de-9103-9546cb9ccb1b)

Output of dlocate grub:
![image](https://github.com/jiangcuo/Proxmox-Port/assets/11367720/cab6dc50-af76-4ecf-8afc-9fffeabf4164)

**Comment by jiangcuo** [comment]
https://github.com/jiangcuo/Proxmox-Port/wiki/Resource_PassThrough
