### ISSUE TITLE
Missing a bunch of packages 

### ISSUE THREAD

**Issue by terrorpup** [jiangcuo/Proxmox-Port#40]
It seems so much is missing, I followed steps for Arm, I am using OrangePi 5 Plus 

root@kitsune:~# cat /etc/os-release
PRETTY_NAME="Orange Pi 1.0.8 Bullseye"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
 
 root@kitsune:~# apt install proxmox-ve postfix open-iscsi
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ceph-common : Depends: librbd1 (= 17.2.6-pve1+3) but it is not going to be installed
               Depends: python3-cephfs (= 17.2.6-pve1+3) but it is not going to be installed
               Depends: python3-rados (= 17.2.6-pve1+3) but it is not going to be installed
               Depends: python3-rbd (= 17.2.6-pve1+3) but it is not going to be installed
               Depends: python3-rgw (= 17.2.6-pve1+3) but it is not going to be installed
               Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
               Depends: libcephfs2 but it is not going to be installed
               Depends: libfmt9 (>= 9.1.0+ds1) but it is not installable
               Depends: libgoogle-perftools4 (>= 2.10) but it is not going to be installed
               Depends: libicu72 (>= 72.1~rc-1~) but it is not installable
               Depends: librados2 but it is not going to be installed
               Depends: libradosstriper1 but it is not going to be installed
               Depends: libsnappy1v5 (>= 1.1.9) but it is not going to be installed
               Depends: libssl3 (>= 3.0.0) but it is not installable
               Depends: libstdc++6 (>= 12) but 10.2.1-6 is to be installed
               Depends: libthrift-0.17.0 (>= 0.17.0-1~) but it is not installable
 ceph-fuse : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
             Depends: libfmt9 (>= 9.1.0+ds1) but it is not installable
             Depends: libfuse3-3 (>= 3.12.0) but 3.10.3-2 is to be installed
             Depends: librados2 but it is not going to be installed
             Depends: libstdc++6 (>= 12) but 10.2.1-6 is to be installed
 libpve-rs-perl : Depends: perl (>= 5.36.0-7) but 5.32.1-4+deb11u2 is to be installed
                  Depends: perlapi-5.36.0 but it is not installable
                  Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
                  Depends: libssl3 (>= 3.0.0) but it is not installable
 libpve-u2f-server-perl : Depends: perl (>= 5.36.0-7) but 5.32.1-4+deb11u2 is to be installed
                          Depends: perlapi-5.36.0 but it is not installable
 librados2-perl : Depends: librados2 (>= 0.67.5) but it is not going to be installed
                  Depends: perl (>= 5.36.0-7) but 5.32.1-4+deb11u2 is to be installed
                  Depends: perlapi-5.36.0 but it is not installable
 lxc-pve : Depends: criu (>= 1.5.2-1) but it is not installable
           Depends: libgnutlsxx30 but it is not installable
           Depends: lxcfs but it is not going to be installed
           Depends: libc6 (>= 2.36) but 2.31-13+deb11u7 is to be installed
           Depends: libssl3 (>= 3.0.0) but it is not installable
 proxmox-backup-client : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
                         Depends: libssl3 (>= 3.0.0) but it is not installable
                         Depends: libzstd1 (>= 1.5.2) but 1.4.8+dfsg-2.1 is to be installed
 proxmox-backup-file-restore : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
                               Depends: libssl3 (>= 3.0.0) but it is not installable
                               Depends: libzstd1 (>= 1.5.2) but 1.4.8+dfsg-2.1 is to be installed
 proxmox-mail-forward : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
 proxmox-mini-journalreader : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
 proxmox-websocket-tunnel : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
                            Depends: libssl3 (>= 3.0.0) but it is not installable
 pve-cluster : Depends: corosync (>= 2.3.4-1) but it is not going to be installed
               Depends: libglib2.0-0 (>= 2.68) but 2.66.8-1 is to be installed
               Depends: perl (>= 5.36.0-7) but 5.32.1-4+deb11u2 is to be installed
               Depends: perlapi-5.36.0 but it is not installable
               Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
               Depends: libcpg4 (>= 2.3.4) but it is not going to be installed
 pve-firewall : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
                Depends: libnfnetlink0 (>= 1.0.2) but 1.0.1-3+b1 is to be installed
 pve-ha-manager : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
 pve-lxc-syscalld : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
 pve-qemu-kvm : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
                Depends: libfdt1 (>= 1.6.1) but 1.6.0-1 is to be installed
                Depends: libglib2.0-0 (>= 2.67.3) but 2.66.8-1 is to be installed
                Depends: libgnutls30 (>= 3.7.5) but 3.7.1-5+deb11u3 is to be installed
                Depends: libnuma1 (>= 2.0.15-1) but it is not going to be installed
                Depends: libproxmox-backup-qemu0 (>= 1.3.0) but it is not going to be installed
                Depends: librados2 but it is not going to be installed
                Depends: librbd1 but it is not going to be installed
                Depends: libslirp0 (>= 4.7.0) but it is not going to be installed
                Depends: liburing2 (>= 2.3) but it is not installable
                Depends: libzstd1 (>= 1.5.2) but 1.4.8+dfsg-2.1 is to be installed
 pve-xtermjs : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
 qemu-server : Depends: swtpm but it is not going to be installed
               Depends: swtpm-tools but it is not going to be installed
               Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
 spiceterm : Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
 vncterm : Depends: libgnutls30 (>= 3.7.5) but 3.7.1-5+deb11u3 is to be installed
           Depends: libc6 (>= 2.34) but 2.31-13+deb11u7 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by DanielAW** [comment]
@terrorpup I have the same issue on a NVIDIA Jetson Orin Nano. Did you get it fixed, if yes, how?
