### ISSUE TITLE
Orangepi5 installation failed.

### ISSUE THREAD

**Issue by nongze** [jiangcuo/Proxmox-Port#43]
**I tried installing PVe7 on Orangepi 5, but it seems to have some issues.**
`>uname -a`
` Linux orangepi5 5.10.110-rockchip-rk3588 #1.1.6 SMP Thu Jun 1 21:23:54 CST 2023 aarch64 GNU/Linux`

`❯ apt install proxmox-ve postfix open-iscsi`
```
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成
open-iscsi 已经是最新版 (2.1.3-5)。
postfix 已经是最新版 (3.5.23-0+deb11u1)。
proxmox-ve 已经是最新版 (7.3-1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 36 个软件包未被升级。
有 2 个软件包没有被完全安装或卸载。
解压缩后会消耗 0 B 的额外空间。
您希望继续执行吗？ [Y/n] y
正在设置 pve-manager (7.4-16) ...
Job for pvestatd.service failed because the control process exited with error code.
See "systemctl status pvestatd.service" and "journalctl -xe" for details.
dpkg: 处理软件包 pve-manager (--configure)时出错：
 已安装 pve-manager 软件包 post-installation 脚本 子进程返回错误状态 1
dpkg: 依赖关系问题使得 proxmox-ve 的配置工作不能继续：
 proxmox-ve 依赖于 pve-manager；然而：
  软件包 pve-manager 尚未配置。

dpkg: 处理软件包 proxmox-ve (--configure)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 pve-manager
 proxmox-ve
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
There are also some other issues (as shown in the picture).
![C0ODHREN0W UH~)_303A`ZK](https://github.com/jiangcuo/Proxmox-Port/assets/110707694/c5053acf-8f19-45aa-8cab-fb7097e35c14)
![Y`EVE85FNP@%EKUOES `)SB](https://github.com/jiangcuo/Proxmox-Port/assets/110707694/a3194c7e-c4a5-4816-ab24-e8609e0e7a61)
![GVTH8XDZ)$0{$SQZ_~E99NK](https://github.com/jiangcuo/Proxmox-Port/assets/110707694/b0868ce4-19f6-4be2-9463-ec3c806e1c96)

![SWU$EY6L21XA)B%ZU%C$P07](https://github.com/jiangcuo/Proxmox-Port/assets/110707694/ae1ee114-8cc6-4f70-a4c8-9a7cba48b312)

I don't know what to do.
Please help me.
Thanks.

**Comment by jiangcuo** [comment]
Follow wiki and set correct /etc/hosts
