### ISSUE TITLE
Very slow download via mirrors.apqa.cn

### ISSUE THREAD

**Issue by kpalatzky** [jiangcuo/Proxmox-Port#46]
**Describe the bug**
I would like to set up my server with Proxmox Port. The installation via mirrors.apqa.cn takes a very long time and only ~30-60 kB/s are achieved on average. This means the installation takes 40-60 minutes.

**To Reproduce**
Run `apt-get install proxmox-ve`

**Expected behavior**
Installation of `proxmox-ve` in under 2 minutes

**Screenshots**

**ENV (please complete the following information):**
 - OS: bookworm
 - ARCH: arm64
 - Version: -

**Additional context**

**Comment by jiangcuo** [comment]
Visit the  site `https://mirrors.apqa.cn` ,you will find cdn-mirrors.
If you are willing to set up a CDN node in your area and share it, I am happy to add the address to the wiki
