### ISSUE TITLE
zfs not loading

### ISSUE THREAD

**Issue by kinhsman** [jiangcuo/Proxmox-Port#5]
Hi, I have Proxmox 8.0.6 running on NanoPi R6S. The issue i'm running into is that I cannot create a ZFS pool. Any insight is greatly appreciated!
<img width="623" alt="image" src="https://github.com/jiangcuo/Proxmox-Port/assets/145226962/a23cdd46-9fd0-41d4-b314-a85bba79e45a">

```
root@NanoPi-PVE:~# zpool list
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
root@NanoPi-PVE:~# /sbin/modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.10.160
root@NanoPi-PVE:~# 
```

**Comment by jiangcuo** [comment]
https://github.com/jiangcuo/Proxmox-Arm64/issues/45

**Comment by LuisPuertollano** [comment]
Hello Jiangcuo, hello evryone,

I`ve followed all linked ressources as resolution but I'm still stucked ...is there any way to have a unified explanation?

actual status is following, I'm triying to create a ZFS Pool for 4x4TB SSDs
![imagen](https://github.com/user-attachments/assets/de813774-7bd0-45e7-a018-c83333d97be1)
