### ISSUE TITLE
Booting Windows 10/11 ARM

### ISSUE THREAD

**Issue by nopmop** [jiangcuo/Proxmox-Port#54]
Has anyone had any success? 
Can you share your `qemu` command line?
Thank you.

**Comment by nopmop** [comment]
> https://github.com/jiangcuo/Proxmox-Port/wiki/Windows-11-arm64

It works, but Windows refuses to load the virtio drivers, even with the registry keys in place.
Do you have any idea how to resolve?

**Comment by jiangcuo** [comment]
This should be a system issue, not a pve issue, so close the issue
