### ISSUE TITLE
pve-port-kernel compatible with raspberry pi 5?

### ISSUE THREAD

**Issue by wuast94** [jiangcuo/Proxmox-Port#59]
as the title said, are the kernals from your other repo pve-port-kernel compatible with raspberry pi 5? using kernel8 seems to make some problems with virtio or dont support it at all

**Comment by abufrejoval** [comment]
If you use UEFI to boot the RP5, the ISO can be used directly.

But you can just use the normal Raspi OS and then follow the steps in his wiki to install Proxmox from the repos.

**Comment by wuast94** [comment]
Had it running but to much problems related to ceph osd`s that went down after some time, so i reused the PI`s. closing this
