### ISSUE TITLE
Can't restore on pve 8.0.6 on raspbery pi 5 from Proxmox Backup Server

### ISSUE THREAD

**Issue by Thimoty44** [jiangcuo/Proxmox-Port#6]
Hi, everyone, the pve on arm product is awesome so I have create a vm to test proxmox backup server with arm too .
I backed up a test vm on the promox backup server 3.0-2 on arm and tried to restore it but I have meet the following error :

 Logical volume "vm-100-disk-1" successfully removed.
  Logical volume "vm-100-disk-0" successfully removed.
  Logical volume "vm-100-disk-0" created.
new volume ID is 'pimox-storage:vm-100-disk-0'
  Logical volume "vm-100-disk-1" created.
new volume ID is 'pimox-storage:vm-100-disk-1'
restore proxmox backup image: /usr/bin/pbs-restore --repository backup@pbs@192.168.50.19:TestPBS vm/100/2023-11-12T12:00:35Z drive-efidisk0.img.fidx /dev/vg-pimox/vm-100-disk-0 --verbose --format raw --skip-zero
connecting to repository 'backup@pbs@192.168.50.19:TestPBS'
open block backend for target '/dev/vg-pimox/vm-100-disk-0'
starting to restore snapshot 'vm/100/2023-11-12T12:00:35Z'
download and verify backup index
restore failed: unable to read fixed index 'drive-efidisk0.img.fidx' - EINVAL: Invalid argument
  Logical volume "vm-100-disk-0" successfully removed.
temporary volume 'pimox-storage:vm-100-disk-0' sucessfuly removed
  Logical volume "vm-100-disk-1" successfully removed.
temporary volume 'pimox-storage:vm-100-disk-1' sucessfuly removed
error before or during data restore, some or all disks were not completely restored. VM 100 state is NOT cleaned up.
TASK ERROR: command '/usr/bin/pbs-restore --repository backup@pbs@192.168.50.19:TestPBS vm/100/2023-11-12T12:00:35Z drive-efidisk0.img.fidx /dev/vg-pimox/vm-100-disk-0 --verbose --format raw --skip-zero' failed: exit code 255

This is possibly a bug because I can backup but not restore on pve 8.0.6 on arm on raspbery pi 5.
Could someone help me with that ?

Have a nice day.

**Comment by Thimoty44** [comment]
I just figured out when I go in file restore on pve I got this error :
cannot run file-restore VM: package 'proxmox-backup-restore-image' is not (correctly) installed (500)

So I tried reinstalled with this command :
apt reinstall proxmox-backup-client proxmox-backup-file-restore --no-install-recommends

But it did not work

**Comment by jiangcuo** [comment]
1. What's your pbs hardware and version.
2. `proxmox-backup-restore-image` is built for x86_64 and I'm trying to port it. I'll reply if there's progress.

**Comment by Thimoty44** [comment]
Hi my pbs version is 3.0-2 from repository : deb https://global.mirrors.apqa.cn/proxmox/debian/pbs bookworm port
I am using debian 12 for arm 
This is a VM create from my pve on arm 
This my conf for the PBS vm :
![image](https://github.com/jiangcuo/Proxmox-Port/assets/29130587/407d686f-a715-4a51-9e0f-ad7cdad7ef54)

**Comment by Thimoty44** [comment]
Hi, after reinstalling for file restore I got the following error :
![image](https://github.com/jiangcuo/Proxmox-Port/assets/29130587/5553355d-ddcb-4083-b695-a68e6bb73596)

With restore same error : 
![image](https://github.com/jiangcuo/Proxmox-Port/assets/29130587/f8292022-43cf-4ede-a0eb-0787e9cf0c91)

I tried this test with a new vm debian 12 arm that I backed up in stop mode after reinstalling packages then tried to restore without sucess.
Have a nice day, I hope this errors could help you.

**Comment by jiangcuo** [comment]
Do you have an x86 machine？
You can use an x86 PBS to backup the ARM VM and restore .
Or backup the x86 VM and restore for test.
Or  install pbs on your host and backup or restore VM.

**Comment by Thimoty44** [comment]
> Do you have an x86 machine？ You can use an x86 PBS to backup the ARM VM and restore . Or backup the x86 VM and restore for test. Or install pbs on your host and backup or restore VM.

Hi, sorry I don't have any vm in x86 or x86 machine but I tried something this a workaround currently if you have a PBS you can mount an NFS on your PBS or any other os and mount it in proxmox : 
![image](https://github.com/jiangcuo/Proxmox-Port/assets/29130587/c266fb97-e2e0-42e0-ac20-33fed57a8915)

And you can restore with the pve : 
![image](https://github.com/jiangcuo/Proxmox-Port/assets/29130587/b0193060-3047-478d-badc-a6044d17a31f)

The only thing is that I had to mount nfs manually in /etc/fstab : 
![image](https://github.com/jiangcuo/Proxmox-Port/assets/29130587/79d57936-93e6-4486-a8bc-803398129d1e)

I added storage by using the directory mode in proxmox : 
![image](https://github.com/jiangcuo/Proxmox-Port/assets/29130587/7c77b19b-8c59-4245-b96c-6be43be04d09)

If u have a problem mounting nfs when rebooting do this in your crontab : 
@reboot /usr/bin/sleep 60 && /usr/bin/systemctl daemon-reload && /usr/bin/mount -a

The only things with this work around we loose the prune and compression of PBS we only use the compression used by the proxmox.
For pruning configure over you backup on Proxmox and when you add the storage as directory.

Hope this workaround could help fort other have a nice day guys.

**Comment by jiangcuo** [comment]
I can't reproduce your problem, there is no problem with the pbs of arm64 on my side.
`file-restore`  has fixed  and It requires the kernel to support vsock.

**Comment by jiangcuo** [comment]
PBS need 4k page size.
