### ISSUE TITLE
apt upgrade fails on debian 12.5 /  PVE 8.1.3+pve1

### ISSUE THREAD

**Issue by sipiyou** [jiangcuo/Proxmox-Port#61]
Everything is running since some weeks fine as I used this howto to install everything on Pi4.

https://github.com/jiangcuo/Proxmox-Port/wiki/Install-Proxmox-VE-on-Debian-bookworm

But today I tried to update the base debian system and I am getting this error:

Do I need to remove something ?

-----
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pve-firmware : Conflicts: firmware-linux-free but 20200122-1 is to be installed
                Conflicts: firmware-linux-free:armhf
E: Broken packages
---

This is what dpkg shows me:

root@pimox:/# dpkg -l | grep -i firmware
ii  bluez-firmware                       1.2-9+rpt2                          all          Firmware for Bluetooth devices
ii  pve-edk2-firmware-aarch64            4.2023.08-2                         all          edk2 based ARM64 UEFI firmware modules for virtual machines
ii  pve-edk2-firmware-legacy             4.2023.08-2                         all          edk2 based legacy 2MB UEFI firmware modules for virtual machines
ii  pve-edk2-firmware-ovmf               4.2023.08-2                         all          edk2 based UEFI firmware modules for virtual machines
ii  pve-firmware                         3.8-1                               all          Binary firmware code for the pve-kernel
ii  raspi-firmware                       1:1.20231024+ds-1+rpt5              all          Raspberry Pi family GPU firmware and bootloaders
ii  rpi-update                           20230904                            all          Raspberry Pi firmware updating tool

-----
root@pimox:/# apt list --upgradeable
Listing... Done
bluez-firmware/stable,stable 1.2-9+rpt3 all [upgradable from: 1.2-9+rpt2]
dphys-swapfile/stable,stable 20100506-7.1+rpt3 all [upgradable from: 20100506-7.1+rpt2]
gtk-update-icon-cache/stable 1:3.24.38-2~deb12u1+rpt4+rpi1 arm64 [upgradable from: 1:3.24.38-2~deb12u1+rpt3+rpi1]
libavcodec59/stable 8:5.1.4-0+rpt3+deb12u1 arm64 [upgradable from: 8:5.1.4-0+rpt2+deb12u1]
libavfilter8/stable 8:5.1.4-0+rpt3+deb12u1 arm64 [upgradable from: 8:5.1.4-0+rpt2+deb12u1]
libavformat59/stable 8:5.1.4-0+rpt3+deb12u1 arm64 [upgradable from: 8:5.1.4-0+rpt2+deb12u1]
libavutil57/stable 8:5.1.4-0+rpt3+deb12u1 arm64 [upgradable from: 8:5.1.4-0+rpt2+deb12u1]
libcamera-apps-lite/stable,stable 1.4.3-1 all [upgradable from: 1.4.2-1]
libcamera-ipa/stable 0.2.0+rpt20240215-1 arm64 [upgradable from: 0.1.0+rpt20231122-1]
libgtk-3-0/stable 1:3.24.38-2~deb12u1+rpt4+rpi1 arm64 [upgradable from: 1:3.24.38-2~deb12u1+rpt3+rpi1]
libgtk-3-bin/stable 1:3.24.38-2~deb12u1+rpt4+rpi1 arm64 [upgradable from: 1:3.24.38-2~deb12u1+rpt3+rpi1]
libgtk-3-common/stable,stable 1:3.24.38-2~deb12u1+rpt4+rpi1 all [upgradable from: 1:3.24.38-2~deb12u1+rpt3+rpi1]
libpisp-common/stable,stable 1.0.4-1 all [upgradable from: 1.0.2-1]
libpisp1/stable 1.0.4-1 arm64 [upgradable from: 1.0.2-1]
libpostproc56/stable 8:5.1.4-0+rpt3+deb12u1 arm64 [upgradable from: 8:5.1.4-0+rpt2+deb12u1]
libswresample4/stable 8:5.1.4-0+rpt3+deb12u1 arm64 [upgradable from: 8:5.1.4-0+rpt2+deb12u1]
libswscale6/stable 8:5.1.4-0+rpt3+deb12u1 arm64 [upgradable from: 8:5.1.4-0+rpt2+deb12u1]
libwayland-client0/stable 1.22.0-2.1~bpo12+rpt1 arm64 [upgradable from: 1.21.0-1]
libwayland-cursor0/stable 1.22.0-2.1~bpo12+rpt1 arm64 [upgradable from: 1.21.0-1]
libwayland-egl1/stable 1.22.0-2.1~bpo12+rpt1 arm64 [upgradable from: 1.21.0-1]
libwayland-server0/stable 1.22.0-2.1~bpo12+rpt1 arm64 [upgradable from: 1.21.0-1]
linux-headers-rpi-2712/stable 1:6.6.20-1+rpt1 arm64 [upgradable from: 1:6.1.73-1+rpt1]
linux-headers-rpi-v8/stable 1:6.6.20-1+rpt1 arm64 [upgradable from: 1:6.1.73-1+rpt1]
linux-image-rpi-2712/stable 1:6.6.20-1+rpt1 arm64 [upgradable from: 1:6.1.73-1+rpt1]
linux-image-rpi-v8/stable 1:6.6.20-1+rpt1 arm64 [upgradable from: 1:6.1.73-1+rpt1]
linux-libc-dev/stable,stable 1:6.6.20-1+rpt1 arm64 [upgradable from: 1:6.1.73-1+rpt1]
raspberrypi-sys-mods/stable 20240129 arm64 [upgradable from: 20240123]
raspi-config/stable,stable 20240313 all [upgradable from: 20240108]
raspi-firmware/stable,stable 1:1.20240306+ds-1+rpt1 all [upgradable from: 1:1.20231024+ds-1+rpt5]
raspi-utils/stable 20240115-1 arm64 [upgradable from: 20231105-1]
rpi-eeprom/stable,stable 21.4-1 all [upgradable from: 21.2-1]
rpicam-apps-lite/stable 1.4.3-1 arm64 [upgradable from: 1.4.2-1]

Thanks so far for your help :)

**Comment by jiangcuo** [comment]
https://github.com/jiangcuo/Proxmox-Arm64/issues/19

**Comment by sipiyou** [comment]
Thanks for your feedback but the problem is still there:

root@pimox:~# apt download pve-firmware
Get:1 https://mirrors.apqa.cn/proxmox/debian/pve bookworm/port arm64 pve-firmware all 3.8-1 [97.3 MB]
Fetched 97.3 MB in 34s (2,824 kB/s)                                                                                                                                                                                                                                                      
W: Download is performed unsandboxed as root as file '/root/pve-firmware_3.8-1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
root@pimox:~# dpkg -i --force-overwrite pve-firmware_*.deb
(Reading database ... 94346 files and directories currently installed.)
Preparing to unpack pve-firmware_3.8-1_all.deb ...
Unpacking pve-firmware (3.8-1) over (3.8-1) ...
Setting up pve-firmware (3.8-1) ...
root@pimox:~# apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease                                                              
Get:2 http://archive.raspberrypi.com/debian bookworm InRelease [23.6 kB]                                           
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]                          
Get:4 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]                                                
Get:6 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [144 kB]
Get:7 http://archive.raspberrypi.com/debian bookworm/main arm64 Packages [374 kB]
Get:8 http://archive.raspberrypi.com/debian bookworm/main armhf Packages [383 kB]
Hit:5 https://mirrors.lierfang.com/proxmox/debian/pve bookworm InRelease                                                                                                                                                                                                                 
Fetched 1,027 kB in 14s (72.9 kB/s)                                                                                                                                                                                                                                                      
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
43 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@pimox:~# apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pve-firmware : Conflicts: firmware-linux-free but 20200122-1 is to be installed
                Conflicts: firmware-linux-free:armhf
E: Broken packages
root@pimox:~#

**Comment by jiangcuo** [comment]
It's been too long, close the issue
