### ISSUE TITLE
GPG signing key curl command download empty file

### ISSUE THREAD

**Issue by UbioZur** [jiangcuo/Proxmox-Port#64]
**Describe the bug**
Following the wiki or the repo.md file inside the help folder. The curl command
`curl https://mirrors.apqa.cn/proxmox/debian/pveport.gpg` download an empty file.

`curl -L https://mirrors.apqa.cn/proxmox/debian/pveport.gpg` download the proper file.

**To Reproduce**
1. `curl https://mirrors.apqa.cn/proxmox/debian/pveport.gpg -o pveport.gpg`
2. cat pveport.gpg
3. File is empty

**Expected behavior**
I am no expert but following other answer from curl issues, it seems to be due to curl not following redirection, so -L need to be added to the curl command.
So the wiki and the help/repo.md file should be fixed.

**Comment by teranex** [comment]
I also just ran into this issue. Adding `-L` to curl fixed it indeed.

**Comment by jiangcuo** [comment]
This issue should be that I have enabled the Cloudflare redirect policy yesterday. I've updated the wiki, thanks for the feedback

**Comment by UbioZur** [comment]
This page also need to be changed (in case people use it instead of the wiki)

https://github.com/jiangcuo/Proxmox-Port/blob/main/help/repo.md

**Comment by jiangcuo** [comment]
> This page also need to be changed (in case people use it instead of the wiki)
> 
> https://github.com/jiangcuo/Proxmox-Port/blob/main/help/repo.md

done

**Comment by UbioZur** [comment]
Thanks, Closing the issue also.
