### ISSUE TITLE
Not sure why this is happening.

### ISSUE THREAD

**Issue by mcooperRPI** [jiangcuo/Proxmox-Port#66]
Hey Guys,

I am trying to create a VM on the host and I am getting this in the syslogs:

`Mar 17 05:17:39 opi5-pve-01 pvestatd[1949]: QEMU/KVM cannot detect CPU flags on ARM (aarch64)
Mar 17 05:17:39 opi5-pve-01 pvestatd[1949]: CPU flag detection failed, will try again after delay`

Can anyone help me please? I do not know how to set the CPU Flags to resolve this. 

This is what I am trying to complete this on:
`Orange Pi 1.1.8 Bookworm with Linux 5.10.160-rockchip-rk3588`
 
And before you ask yes I installed everything via your instructions.
`1  5  echo 'deb [arch=arm64] https://mirrors.apqa.cn/proxmox/debian/pve bookworm port'>/etc/apt/sources.list.d/pveport.list
    6  curl -L https://mirrors.apqa.cn/proxmox/debian/pveport.gpg -o /etc/apt/trusted.gpg.d/pveport.gpg 
    7  apt update && apt -y full-upgrade
    8  apt -y install ifupdown2
    9  apt -y install proxmox-ve postfix open-iscsi
   10  apt download pve-edk2-firmware-aarch64=3.20220526-rockchip
   11  dpkg -i pve-edk2-firmware-aarch64_3.20220526-rockchip_all.deb
   16  nano -c /etc/network/interfaces
   23  apt download pve-edk2-firmware-aarch64=3.20220526-rockchip
   24  dpkg -i pve-edk2-firmware-aarch64_3.20220526-rockchip_all.deb`

Thanks guys,
Michael

**Comment by jiangcuo** [comment]
ignore message

**Comment by jiangcuo** [comment]
No update, close it
