### ISSUE TITLE
Update Support List - Add OrangePI CM4 (/w Base) Works Fine

### ISSUE THREAD

**Issue by nikos445** [jiangcuo/Proxmox-Port#73]
Add in your Support list the following Device (OrangePI CM4) (arm64) ... 

tested and working fine...
 + OrangePI Base + CM4 

Specs: 

>  4 cores 
> 8GB RAM 
> 64GB EMMC 
 
 - Quick installation instructions
 ```
 Balena etcher => flash sd card with debian...
 Boot sd card and flash emmc with debian (img)...
 Shutdown and remove sd card
 Boot Debian from EMMC 
 Follow instructions for installing Proxmox from repository (add repo + update + install pve packages)
 Follow instructions for Rockchip pve-edk-firmware...
 Follow instructions for starting a QEMU VM (wget+import) 
 ```
 
 - Tested uploading images to local storage (emmc) and create vm from UI (doesnt work for some reason in SEABIOS there is no display and in UEFI it doesn't find boot devices.)

**Comment by dandycyclone** [comment]
Actually this comment/problem is still valid - and even with OrangePI 5:
 - _Tested uploading images to local storage (emmc) and create vm from UI (**doesnt work for some reason in SEABIOS there is no display and in UEFI it doesn't find boot devices.**)_

SeaBIOS "no display" problem is yet to be debugged, but for "in UEFI it doesn't find boot devices" this workaround could be used so far: https://mricher.fr/post/boot-from-an-efi-shell/

Note:
 - official recommendation from Proxmox using EFI disk to preserve efivars and as such boot order did not really help me: https://forum.proxmox.com/threads/purpose-of-the-efi-disk.53862/
