### ISSUE TITLE
OrangePi 5 Plus UEFI install

### ISSUE THREAD

**Issue by arunas-smala** [jiangcuo/Proxmox-Port#74]
`note: by now 2024.4.1. only orangepi 5 support.`

I see note that only orangepi 5 is supported. How about "Plus" version?

I'm getting an error like "PCIe Link Fail" "tailed to initialize host" or something, so thinking if I'm doing something wrong or it is not supported yet, thanks

**Comment by jiangcuo** [comment]
Support Orangepi 5 all  series.
Ignore this error message.

**Comment by arunas-smala** [comment]
Solved!
I was stuck as the installation ended up in the command prompt after those errors. The problem was that my NVMe wasn't installed properly, after removing and inserting it again - everything went smoothly! amazing job with this port, thanks!
