### ISSUE TITLE
UEFI boot on Orange Pi 5

### ISSUE THREAD

**Issue by lonacluka** [jiangcuo/Proxmox-Port#83]
Hi! I'm trying to boot pve-installer in UEFI mode using the instructions here:

https://github.com/jiangcuo/Proxmox-Port/wiki/Rockchip-RK3588-UEFI-Setup

And everytime the installer (Rockchip Install boot option) boots to busybox with no particular errors visible in the output.

I'm using UEFI firmware for Orange Pi 5 burned to SPI. All UEFI settings applied as instructed on Wiki, and checked that they saved/applied after reboot.

https://github.com/edk2-porting/edk2-rk3588/releases/download/v0.9.1/orangepi-5_UEFI_Release_v0.9.1.img

Using the latest UEFI fw for Opi 5. I successfully booted this Armbian UEFI live iso https://github.com/amazingfate/rk3588-live-iso/releases with no issues

**Comment by arunas-smala** [comment]
https://github.com/jiangcuo/Proxmox-Port/issues/74

I'm not sure if it was the same case, but I always ended up in the command prompt, no install GUI or something. 

First I reinstalled NVMe and suddenly it worked out! Later I got the same while trying to reinstall, so I switched USB stick with proxmox iso to other USB port and it worked! 

Would suggest to try flashing ISO to other media, try other USB port also. Good luck, after install it works perfectly fine! (didn't try USB ports tho)

**Comment by Pix13** [comment]
I have the same issue, tried the usb2 ports without success ( no disk detected), and the usb-c one did not detect the usb key too, and on the two usb3-A ports it boots too directly to busuybox. I'm trying first to see which device is not detected in case it could help later
