### ISSUE TITLE
RPi5 - CT - not showing RAM/SWAP usage.

### ISSUE THREAD

**Issue by s4per** [jiangcuo/Proxmox-Port#9]
Hello everyone.

RPi5 with PROXMOX VE 8.0.6 on the latest RaspberryOS.

In the container summary memory usage and swap usage always shows 0. 

![obraz](https://github.com/jiangcuo/Proxmox-Port/assets/16806919/f860b408-0dac-41d5-b7cb-c050535f8e44)

I checked CT of Debian, Ubuntu, and Alpine. Same problem everywhere. The same container on RPi4 with Pimox 7 works as expected.

Regards!

**Comment by jiangcuo** [comment]
https://github.com/jiangcuo/Proxmox-Arm64/issues/51#issuecomment-1772020210

**Comment by s4per** [comment]
Works perfect.
Thanks a lot!
