### ISSUE TITLE
Update to 8.2 ?

### ISSUE THREAD

**Issue by cfouche3005** [jiangcuo/Proxmox-Port#97]
IAM new to this project but I wanted to ask when the packages for Proxmox 8.2 and the kernel 6.8 will be available ?
Thank for your hard work.

**Comment by jiangcuo** [comment]
done

**Comment by SuperKali** [comment]
@jiangcuo thank you for the support, i've updated my arm cluster <3

**Comment by cfouche3005** [comment]
thank you @jiangcuo, I will close the issue. Is it possible to have the 6.8 kernel ?

**Comment by SQuent** [comment]
Hello, 
Is it possible to have the iso file for Proxmox 8.2 available in repository ? Or how can I create it by myself ? 

I want to test it with the new way of automated install from the ISO with answer file.
Thank you for the work!
