### ISSUE TITLE
Partition does not exist - Raspberry pi 5 Imager

### ISSUE THREAD

**Issue by DanieleMassa** [jiangcuo/Proxmox-Port#99]
After downloading the ISO from this repo and flashing it with the official raspberry tool, I get "Partition does not exist" (in the image below). I've already tried to format the sdcard using gparted before flashing it, nothing changed tho. For reference, I'm using a rpi5 with 8GB of ram (powered by the official power supply) and a SDSQXA1-128G-GN6MN as sdcard
![immagine](https://github.com/jiangcuo/Proxmox-Port/assets/90097496/54f95645-2a2e-4ec7-b598-acba682dbfe2)

**Comment by SuperKali** [comment]
@DanieleMassa There are no specific images for proxmox at the moment, use armbian and install proxmox via repository.
- https://github.com/jiangcuo/Proxmox-Port/wiki/Install-or-upgrade-from-repo
- https://github.com/armbian/community/releases/download/24.8.0-trunk.139/Armbian_community_24.8.0-trunk.139_Rpi5b_bookworm_current_6.6.33_minimal.img.xz

**Comment by DatHardie** [comment]
> @DanieleMassa There are no specific images for proxmox at the moment, use armbian and install proxmox via repository.
> 
> * https://github.com/jiangcuo/Proxmox-Port/wiki/Install-or-upgrade-from-repo
> * https://github.com/armbian/community/releases/download/24.8.0-trunk.139/Armbian_community_24.8.0-trunk.139_Rpi5b_bookworm_current_6.6.33_minimal.img.xz

Is something similar as the armbian installer existing for the Raspberry Pi 4?

**Comment by DanieleMassa** [comment]
> > @DanieleMassa There are no specific images for proxmox at the moment, use armbian and install proxmox via repository.
> > 
> > * https://github.com/jiangcuo/Proxmox-Port/wiki/Install-or-upgrade-from-repo
> > * https://github.com/armbian/community/releases/download/24.8.0-trunk.139/Armbian_community_24.8.0-trunk.139_Rpi5b_bookworm_current_6.6.33_minimal.img.xz
> 
> Is something similar as the armbian installer existing for the Raspberry Pi 4?

the armbian installer works also for rpi4, check [this link](https://www.armbian.com/rpi4/). If you want to install proxmox on it, check [this guide](https://github.com/DanieleMassa/proxmoxOnRPI5) I've written, should work fine also on rpi4
